version: '3.9'
services:
  apache:
    image: httpd:2.4-alpine
    container_name: food
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 128m
        max-file: "1"
        labels: "container_log_status"
        env: "os"
    expose:
      - 443
      - 80
    ports:
      - '80:80'
    volumes:
      - ~/websites/food/:/usr/local/apache2/htdocs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

